language: node_js
compiler:
  - gcc
  - clang
node_js:
  - "stable"
sudo: required
before_script:
  - git clone https://github.com/google/jsonnet
  - cd jsonnet
  - set -e
  - make test
  - python setup.py build
  - sudo python setup.py install
  - ( cd python ; ./run_tests.sh )
  - cd ../..
  - cp jsonnet/jsonnet node_modules/jsonnet-exec/bin/
script:
  - npm run test
